apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: fancy.azurecr.io/nodeapp:latest
        ports:
        - containerPort: 8080
          name: http
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

--- 

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodeapp
  type: LoadBalancer
